/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'title' : string,
  'content' : string,
  'keyPoints' : Array<string>,
}
export interface Module {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'questions' : Array<Question>,
  'orderIndex' : bigint,
}
export interface Question {
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface UserProfile {
  'age' : bigint,
  'name' : string,
  'location' : string,
}
export interface UserProgress {
  'moduleScores' : Array<[bigint, bigint]>,
  'totalScore' : bigint,
  'completedLessons' : Array<bigint>,
  'certified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLesson' : ActorMethod<[bigint, Lesson], undefined>,
  'addModule' : ActorMethod<[string, string, bigint], bigint>,
  'addQuestion' : ActorMethod<[bigint, Question], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeLesson' : ActorMethod<[bigint, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[Principal], UserProgress>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuiz' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];